# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b1a85ee3ac53c060ae14e87437423c2cd6ee9fba66bde303503d1a192850bd835061eccf24faf20bde001ece1da2b4a7346b51a2c93e24b8c344a1e4bce742a

test:
  secret_key_base: 1a5c4f8d08b0eb3ec72a74d5354db55a491ba0a98aee0ce950e63ce6cc04349a4b7c9b4d7ae90f5048922f168bb81582335b1d704820d96d21cda0db16665d72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
